//*****************************************************************************
//*****************************************************************************
//  FILENAME: Motor3.h
//   Version: 2.5, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 Motor3_EnableInt
#pragma fastcall16 Motor3_DisableInt
#pragma fastcall16 Motor3_Start
#pragma fastcall16 Motor3_Stop
#pragma fastcall16 Motor3_wReadCounter              // Read  DR0
#pragma fastcall16 Motor3_WritePeriod               // Write DR1
#pragma fastcall16 Motor3_wReadPulseWidth           // Read  DR2
#pragma fastcall16 Motor3_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wMotor3_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wMotor3_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Motor3 API.
//-------------------------------------------------

extern void Motor3_EnableInt(void);                  // Proxy Class 1
extern void Motor3_DisableInt(void);                 // Proxy Class 1
extern void Motor3_Start(void);                      // Proxy Class 1
extern void Motor3_Stop(void);                       // Proxy Class 1
extern WORD Motor3_wReadCounter(void);               // Proxy Class 2
extern void Motor3_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD Motor3_wReadPulseWidth(void);            // Proxy Class 1
extern void Motor3_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wMotor3_ReadCounter(void);            // Deprecated
extern WORD wMotor3_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for Motor3 API's.
//-------------------------------------------------

#define Motor3_CONTROL_REG_START_BIT           ( 0x01 )
#define Motor3_INT_REG_ADDR                    ( 0x0e1 )
#define Motor3_INT_MASK                        ( 0x20 )


//--------------------------------------------------
// Constants for Motor3 user defined values
//--------------------------------------------------

#define Motor3_PERIOD                          ( 0x4e1f )
#define Motor3_PULSE_WIDTH                     ( 0x7cf )


//-------------------------------------------------
// Register Addresses for Motor3
//-------------------------------------------------

#pragma ioport  Motor3_COUNTER_LSB_REG: 0x030              //DR0 Count register LSB
BYTE            Motor3_COUNTER_LSB_REG;
#pragma ioport  Motor3_COUNTER_MSB_REG: 0x034              //DR0 Count register MSB
BYTE            Motor3_COUNTER_MSB_REG;
#pragma ioport  Motor3_PERIOD_LSB_REG:  0x031              //DR1 Period register LSB
BYTE            Motor3_PERIOD_LSB_REG;
#pragma ioport  Motor3_PERIOD_MSB_REG:  0x035              //DR1 Period register MSB
BYTE            Motor3_PERIOD_MSB_REG;
#pragma ioport  Motor3_COMPARE_LSB_REG: 0x032              //DR2 Compare register LSB
BYTE            Motor3_COMPARE_LSB_REG;
#pragma ioport  Motor3_COMPARE_MSB_REG: 0x036              //DR2 Compare register MSB
BYTE            Motor3_COMPARE_MSB_REG;
#pragma ioport  Motor3_CONTROL_LSB_REG: 0x033              //Control register LSB
BYTE            Motor3_CONTROL_LSB_REG;
#pragma ioport  Motor3_CONTROL_MSB_REG: 0x037              //Control register MSB
BYTE            Motor3_CONTROL_MSB_REG;
#pragma ioport  Motor3_FUNC_LSB_REG:    0x130              //Function register LSB
BYTE            Motor3_FUNC_LSB_REG;
#pragma ioport  Motor3_FUNC_MSB_REG:    0x134              //Function register MSB
BYTE            Motor3_FUNC_MSB_REG;
#pragma ioport  Motor3_INPUT_LSB_REG:   0x131              //Input register LSB
BYTE            Motor3_INPUT_LSB_REG;
#pragma ioport  Motor3_INPUT_MSB_REG:   0x135              //Input register MSB
BYTE            Motor3_INPUT_MSB_REG;
#pragma ioport  Motor3_OUTPUT_LSB_REG:  0x132              //Output register LSB
BYTE            Motor3_OUTPUT_LSB_REG;
#pragma ioport  Motor3_OUTPUT_MSB_REG:  0x136              //Output register MSB
BYTE            Motor3_OUTPUT_MSB_REG;
#pragma ioport  Motor3_INT_REG:       0x0e1                //Interrupt Mask Register
BYTE            Motor3_INT_REG;


//-------------------------------------------------
// Motor3 Macro 'Functions'
//-------------------------------------------------

#define Motor3_Start_M \
   ( Motor3_CONTROL_LSB_REG |=  Motor3_CONTROL_REG_START_BIT )

#define Motor3_Stop_M  \
   ( Motor3_CONTROL_LSB_REG &= ~Motor3_CONTROL_REG_START_BIT )

#define Motor3_EnableInt_M   \
   M8C_EnableIntMask(  Motor3_INT_REG, Motor3_INT_MASK )

#define Motor3_DisableInt_M  \
   M8C_DisableIntMask( Motor3_INT_REG, Motor3_INT_MASK )

// end of file Motor3.h
