/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "Motor1.h"
#include "Motor2.h"
#include "Motor3.h"
#include "UART.h"

#endif
