//*****************************************************************************
//*****************************************************************************
//  FILENAME: Motor1.h
//   Version: 2.5, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 Motor1_EnableInt
#pragma fastcall16 Motor1_DisableInt
#pragma fastcall16 Motor1_Start
#pragma fastcall16 Motor1_Stop
#pragma fastcall16 Motor1_wReadCounter              // Read  DR0
#pragma fastcall16 Motor1_WritePeriod               // Write DR1
#pragma fastcall16 Motor1_wReadPulseWidth           // Read  DR2
#pragma fastcall16 Motor1_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wMotor1_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wMotor1_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Motor1 API.
//-------------------------------------------------

extern void Motor1_EnableInt(void);                  // Proxy Class 1
extern void Motor1_DisableInt(void);                 // Proxy Class 1
extern void Motor1_Start(void);                      // Proxy Class 1
extern void Motor1_Stop(void);                       // Proxy Class 1
extern WORD Motor1_wReadCounter(void);               // Proxy Class 2
extern void Motor1_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD Motor1_wReadPulseWidth(void);            // Proxy Class 1
extern void Motor1_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wMotor1_ReadCounter(void);            // Deprecated
extern WORD wMotor1_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for Motor1 API's.
//-------------------------------------------------

#define Motor1_CONTROL_REG_START_BIT           ( 0x01 )
#define Motor1_INT_REG_ADDR                    ( 0x0e1 )
#define Motor1_INT_MASK                        ( 0x02 )


//--------------------------------------------------
// Constants for Motor1 user defined values
//--------------------------------------------------

#define Motor1_PERIOD                          ( 0x4e1f )
#define Motor1_PULSE_WIDTH                     ( 0x3e7 )


//-------------------------------------------------
// Register Addresses for Motor1
//-------------------------------------------------

#pragma ioport  Motor1_COUNTER_LSB_REG: 0x020              //DR0 Count register LSB
BYTE            Motor1_COUNTER_LSB_REG;
#pragma ioport  Motor1_COUNTER_MSB_REG: 0x024              //DR0 Count register MSB
BYTE            Motor1_COUNTER_MSB_REG;
#pragma ioport  Motor1_PERIOD_LSB_REG:  0x021              //DR1 Period register LSB
BYTE            Motor1_PERIOD_LSB_REG;
#pragma ioport  Motor1_PERIOD_MSB_REG:  0x025              //DR1 Period register MSB
BYTE            Motor1_PERIOD_MSB_REG;
#pragma ioport  Motor1_COMPARE_LSB_REG: 0x022              //DR2 Compare register LSB
BYTE            Motor1_COMPARE_LSB_REG;
#pragma ioport  Motor1_COMPARE_MSB_REG: 0x026              //DR2 Compare register MSB
BYTE            Motor1_COMPARE_MSB_REG;
#pragma ioport  Motor1_CONTROL_LSB_REG: 0x023              //Control register LSB
BYTE            Motor1_CONTROL_LSB_REG;
#pragma ioport  Motor1_CONTROL_MSB_REG: 0x027              //Control register MSB
BYTE            Motor1_CONTROL_MSB_REG;
#pragma ioport  Motor1_FUNC_LSB_REG:    0x120              //Function register LSB
BYTE            Motor1_FUNC_LSB_REG;
#pragma ioport  Motor1_FUNC_MSB_REG:    0x124              //Function register MSB
BYTE            Motor1_FUNC_MSB_REG;
#pragma ioport  Motor1_INPUT_LSB_REG:   0x121              //Input register LSB
BYTE            Motor1_INPUT_LSB_REG;
#pragma ioport  Motor1_INPUT_MSB_REG:   0x125              //Input register MSB
BYTE            Motor1_INPUT_MSB_REG;
#pragma ioport  Motor1_OUTPUT_LSB_REG:  0x122              //Output register LSB
BYTE            Motor1_OUTPUT_LSB_REG;
#pragma ioport  Motor1_OUTPUT_MSB_REG:  0x126              //Output register MSB
BYTE            Motor1_OUTPUT_MSB_REG;
#pragma ioport  Motor1_INT_REG:       0x0e1                //Interrupt Mask Register
BYTE            Motor1_INT_REG;


//-------------------------------------------------
// Motor1 Macro 'Functions'
//-------------------------------------------------

#define Motor1_Start_M \
   ( Motor1_CONTROL_LSB_REG |=  Motor1_CONTROL_REG_START_BIT )

#define Motor1_Stop_M  \
   ( Motor1_CONTROL_LSB_REG &= ~Motor1_CONTROL_REG_START_BIT )

#define Motor1_EnableInt_M   \
   M8C_EnableIntMask(  Motor1_INT_REG, Motor1_INT_MASK )

#define Motor1_DisableInt_M  \
   M8C_DisableIntMask( Motor1_INT_REG, Motor1_INT_MASK )

// end of file Motor1.h
