//*****************************************************************************
//*****************************************************************************
//  FILENAME: Motor2.h
//   Version: 2.5, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 Motor2_EnableInt
#pragma fastcall16 Motor2_DisableInt
#pragma fastcall16 Motor2_Start
#pragma fastcall16 Motor2_Stop
#pragma fastcall16 Motor2_wReadCounter              // Read  DR0
#pragma fastcall16 Motor2_WritePeriod               // Write DR1
#pragma fastcall16 Motor2_wReadPulseWidth           // Read  DR2
#pragma fastcall16 Motor2_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wMotor2_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wMotor2_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Motor2 API.
//-------------------------------------------------

extern void Motor2_EnableInt(void);                  // Proxy Class 1
extern void Motor2_DisableInt(void);                 // Proxy Class 1
extern void Motor2_Start(void);                      // Proxy Class 1
extern void Motor2_Stop(void);                       // Proxy Class 1
extern WORD Motor2_wReadCounter(void);               // Proxy Class 2
extern void Motor2_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD Motor2_wReadPulseWidth(void);            // Proxy Class 1
extern void Motor2_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wMotor2_ReadCounter(void);            // Deprecated
extern WORD wMotor2_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for Motor2 API's.
//-------------------------------------------------

#define Motor2_CONTROL_REG_START_BIT           ( 0x01 )
#define Motor2_INT_REG_ADDR                    ( 0x0e1 )
#define Motor2_INT_MASK                        ( 0x08 )


//--------------------------------------------------
// Constants for Motor2 user defined values
//--------------------------------------------------

#define Motor2_PERIOD                          ( 0x4e1f )
#define Motor2_PULSE_WIDTH                     ( 0x5db )


//-------------------------------------------------
// Register Addresses for Motor2
//-------------------------------------------------

#pragma ioport  Motor2_COUNTER_LSB_REG: 0x028              //DR0 Count register LSB
BYTE            Motor2_COUNTER_LSB_REG;
#pragma ioport  Motor2_COUNTER_MSB_REG: 0x02c              //DR0 Count register MSB
BYTE            Motor2_COUNTER_MSB_REG;
#pragma ioport  Motor2_PERIOD_LSB_REG:  0x029              //DR1 Period register LSB
BYTE            Motor2_PERIOD_LSB_REG;
#pragma ioport  Motor2_PERIOD_MSB_REG:  0x02d              //DR1 Period register MSB
BYTE            Motor2_PERIOD_MSB_REG;
#pragma ioport  Motor2_COMPARE_LSB_REG: 0x02a              //DR2 Compare register LSB
BYTE            Motor2_COMPARE_LSB_REG;
#pragma ioport  Motor2_COMPARE_MSB_REG: 0x02e              //DR2 Compare register MSB
BYTE            Motor2_COMPARE_MSB_REG;
#pragma ioport  Motor2_CONTROL_LSB_REG: 0x02b              //Control register LSB
BYTE            Motor2_CONTROL_LSB_REG;
#pragma ioport  Motor2_CONTROL_MSB_REG: 0x02f              //Control register MSB
BYTE            Motor2_CONTROL_MSB_REG;
#pragma ioport  Motor2_FUNC_LSB_REG:    0x128              //Function register LSB
BYTE            Motor2_FUNC_LSB_REG;
#pragma ioport  Motor2_FUNC_MSB_REG:    0x12c              //Function register MSB
BYTE            Motor2_FUNC_MSB_REG;
#pragma ioport  Motor2_INPUT_LSB_REG:   0x129              //Input register LSB
BYTE            Motor2_INPUT_LSB_REG;
#pragma ioport  Motor2_INPUT_MSB_REG:   0x12d              //Input register MSB
BYTE            Motor2_INPUT_MSB_REG;
#pragma ioport  Motor2_OUTPUT_LSB_REG:  0x12a              //Output register LSB
BYTE            Motor2_OUTPUT_LSB_REG;
#pragma ioport  Motor2_OUTPUT_MSB_REG:  0x12e              //Output register MSB
BYTE            Motor2_OUTPUT_MSB_REG;
#pragma ioport  Motor2_INT_REG:       0x0e1                //Interrupt Mask Register
BYTE            Motor2_INT_REG;


//-------------------------------------------------
// Motor2 Macro 'Functions'
//-------------------------------------------------

#define Motor2_Start_M \
   ( Motor2_CONTROL_LSB_REG |=  Motor2_CONTROL_REG_START_BIT )

#define Motor2_Stop_M  \
   ( Motor2_CONTROL_LSB_REG &= ~Motor2_CONTROL_REG_START_BIT )

#define Motor2_EnableInt_M   \
   M8C_EnableIntMask(  Motor2_INT_REG, Motor2_INT_MASK )

#define Motor2_DisableInt_M  \
   M8C_DisableIntMask( Motor2_INT_REG, Motor2_INT_MASK )

// end of file Motor2.h
